import { nanoid } from "nanoid";
const data = [
  {
    id: 1,
    img: require("./images/entertainment-low-res.jpg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "office",
    company: "marcos",
    color: "red",
    available: "in stock",
    SKU: nanoid(),
    reviews: 24,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 2,
    img: require("./images/chair-low-res.jpg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "living room",
    company: "liddy",
    color: "green",
    available: "in stock",
    SKU: nanoid(),
    reviews: 30,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 3,
    img: require("./images/bookshelf-low-res.jpg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kitchen",
    company: "ikea",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 50,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 4,
    img: require("./images/product-1.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "bedroom",
    company: "caressa",
    color: "black",
    available: "in stock",
    SKU: nanoid(),
    reviews: 48,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 5,
    img: require("./images/product-2.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "dining",
    company: "marcos",
    color: "yellow",
    available: "in stock",
    SKU: nanoid(),
    reviews: 35,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 6,
    img: require("./images/product-3.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kids",
    company: "liddy",
    color: "red",
    available: "in stock",
    SKU: nanoid(),
    reviews: 19,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 7,
    img: require("./images/product-4.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "office",
    company: "ikea",
    color: "green",
    available: "in stock",
    SKU: nanoid(),
    reviews: 45,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 8,
    img: require("./images/product-5.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "living room",
    company: "caressa",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 37,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 9,
    img: require("./images/product-6.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kitchen",
    company: "marcos",
    color: "black",
    available: "in stock",
    SKU: nanoid(),
    reviews: 17,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 10,
    img: require("./images/product-7.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "bedroom",
    company: "liddy",
    available: "in stock",
    SKU: nanoid(),
    reviews: 46,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 11,
    img: require("./images/product-8.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "dining",
    company: "ikea",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 40,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 12,
    img: require("./images/product-9.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kids",
    company: "caressa",
    color: "black",
    available: "in stock",
    SKU: nanoid(),
    reviews: 47,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 13,
    img: require("./images/product-10.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "office",
    company: "marcos",
    color: "yellow",
    available: "in stock",
    SKU: nanoid(),
    reviews: 29,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 14,
    img: require("./images/product-11.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "living room",
    company: "liddy",
    color: "red",
    available: "in stock",
    SKU: nanoid(),
    reviews: 56,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 15,
    img: require("./images/product-12.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kitchen",
    company: "caressa",
    color: "green",
    available: "in stock",
    SKU: nanoid(),
    reviews: 19,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 16,
    img: require("./images/product-13.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "bedroom",
    company: "marcos",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 55,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 17,
    img: require("./images/product-14.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "dining",
    company: "liddy",
    color: "black",
    available: "in stock",
    SKU: nanoid(),
    reviews: 44,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 18,
    img: require("./images/product-15.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kids",
    company: "ikea",
    color: "yellow",
    available: "in stock",
    SKU: nanoid(),
    reviews: 12,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 19,
    img: require("./images/product-16.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "office",
    company: "caressa",
    color: "red",
    available: "in stock",
    SKU: nanoid(),
    reviews: 43,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 20,
    img: require("./images/product-17.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "living room",
    company: "marcos",
    color: "green",
    available: "in stock",
    SKU: nanoid(),
    reviews: 17,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 21,
    img: require("./images/product-18.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kitchen",
    company: "liddy",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 29,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 22,
    img: require("./images/product-19.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "bedroom",
    company: "ikea",
    color: "black",
    available: "in stock",
    SKU: nanoid(),
    reviews: 39,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 23,
    img: require("./images/product-20.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "dining",
    company: "caressa",
    color: "yellow",
    available: "in stock",
    SKU: nanoid(),
    reviews: 38,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 24,
    img: require("./images/product-21.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "kids",
    company: "marcos",
    color: "red",
    available: "in stock",
    SKU: nanoid(),
    reviews: 36,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 25,
    img: require("./images/product-22.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "office",
    company: "liddy",
    color: "green",
    available: "in stock",
    SKU: nanoid(),
    reviews: 22,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
  {
    id: 26,
    img: require("./images/product-23.jpeg"),
    heading: "Entertainment Center",
    price: 599.99,
    rating: 4,
    category: "living room",
    company: "ikea",
    color: "blue",
    available: "in stock",
    SKU: nanoid(),
    reviews: 37,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus maiores veritatis accusamus hic esse, enim consectetur eveniet molestiae quos est, voluptas aut veniam nulla laboriosam minima fugit quidem magnam dolore sed culpa repudiandae. Id, perspiciatis facere!",
  },
];

export default data;
